# Generated by Django 5.1.7 on 2025-10-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField(help_text='Temperatura en grados Celsius')),
                ('humedad', models.FloatField(help_text='Humedad relativa en porcentaje (0-100)')),
                ('presion', models.FloatField(help_text='Presión atmosférica en hPa')),
                ('velocidad_viento', models.FloatField(help_text='Velocidad del viento en km/h')),
                ('altura', models.FloatField(help_text='Altura sobre el nivel del mar en metros')),
                ('nubosidad', models.FloatField(help_text='Nubosidad en porcentaje (0-100)')),
                ('latitud', models.FloatField(help_text='Latitud en grados decimales')),
                ('longitud', models.FloatField(help_text='Longitud en grados decimales')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
