# Generated by Django 4.2.7 on 2025-10-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroclima',
            name='altura_capa_mezcla',
            field=models.FloatField(default=0.0, help_text='Altura de la capa de mezcla en metros'),
        ),
        migrations.AddField(
            model_name='registroclima',
            name='aod',
            field=models.FloatField(default=0.0, help_text='Profundidad óptica de aerosoles (AOD)'),
        ),
        migrations.AddField(
            model_name='registroclima',
            name='densidad_polvo',
            field=models.FloatField(default=0.0, help_text='Densidad del polvo en µg/m³'),
        ),
        migrations.AddField(
            model_name='registroclima',
            name='desviacion_diametro',
            field=models.FloatField(default=0.0, help_text='Desviación estándar del diámetro en µm'),
        ),
        migrations.AddField(
            model_name='registroclima',
            name='diametro_medio',
            field=models.FloatField(default=0.0, help_text='Diámetro medio de partículas en µm'),
        ),
        migrations.AddField(
            model_name='registroclima',
            name='pm10',
            field=models.FloatField(default=0.0, help_text='PM10 en µg/m³'),
        ),
        migrations.AddField(
            model_name='registroclima',
            name='pm25',
            field=models.FloatField(default=0.0, help_text='PM2.5 en µg/m³'),
        ),
        migrations.AddField(
            model_name='registroclima',
            name='visibilidad',
            field=models.FloatField(default=0.0, help_text='Visibilidad atmosférica en km'),
        ),
    ]
