# Generated by Django 4.2.7 on 2025-10-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0002_registroclima_altura_capa_mezcla_registroclima_aod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroclima',
            name='nombre_lugar',
            field=models.CharField(blank=True, help_text='Nombre del lugar donde se realizó el cálculo', max_length=200),
        ),
    ]
