# Generated by Django 4.2.7 on 2025-10-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0003_registroclima_nombre_lugar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Nombre de usuario', max_length=50, unique=True)),
                ('password', models.CharField(help_text='Contraseña (hash)', max_length=100)),
                ('email', models.EmailField(help_text='Correo electrónico', max_length=254)),
                ('nombre_completo', models.CharField(help_text='Nombre completo del usuario', max_length=100)),
                ('rol', models.CharField(default='investigador', help_text='Rol del usuario (investigador, admin)', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Usuario activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Login',
                'verbose_name_plural': 'Logins',
            },
        ),
    ]
